// Generated by Wrangler by running `wrangler types`

interface Env {
	ICON_CATALOG: KVNamespace;
	TELEMETRY_ENABLED: "true";
	DASHBOARD_ENABLED: "true";
	LOG_LEVEL: "INFO";
	AI_ENABLED: "true";
	SEMANTIC_SEARCH_ENABLED: "true";
	INTENT_CLASSIFICATION_ENABLED: "true";
	SHARED_SECRET: string;
	REGION_COORDINATOR: DurableObjectNamespace /* RegionCoordinatorDO */;
	ANALYTICS_ENGINE: AnalyticsEngineDataset;
	AI: Ai;
}
